import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
let seed=305;
const math=Object.create(Math);math.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
const store=new Map(),element={innerHTML:'',textContent:'',classList:{toggle(){},add(){},remove(){}},getContext:()=>({setTransform(){}}),dataset:{},style:{},insertAdjacentHTML(){}};
const sandbox={console,Math:math,document:{body:element,hidden:false,addEventListener(){},querySelector:()=>element,querySelectorAll:()=>[],getElementById:()=>element},window:{scrollTo(){}},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},matchMedia:()=>({matches:false}),setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},requestAnimationFrame:()=>1,cancelAnimationFrame(){},devicePixelRatio:1,performance:{now:()=>0},Image:function(){},btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary')};
vm.createContext(sandbox);
for(const file of ['game.js','portrait-frames.js','polish.js','identity.js','cinema.js','score.js','tactics.js','formation-drag.js','club-flow.js','campaign.js','assets/vendor/three.min.js','beast-materials.js','beast-sculpt.js','beasts-3d.js','onboarding.js','arena-flow.js','arena-growth.js','run-menu.js','league-desk.js','autobattle.js','battle-audio.js','roster-desk.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),sandbox,{filename:file});
const run=code=>vm.runInContext(code,sandbox);
run(`render=()=>{};renderModal=()=>{};renderTop=()=>{};renderTabs=()=>{};toast=()=>{};music=()=>{};playCue=()=>{};
function fresh(name='Test Campaign'){resetRunUI();UI.mode='hub';newGame(name,CASTS[0].m,38);G.onboarding.active=false;const ids=G.market.slice(0,8);G.gold=3000;for(const id of ids)ACT.buy({id});G.gold=0;return G}
function resultFor(winner=0){const S=createSim(UI.sel.map(id=>G.beasts[id]),pickLineup(UI.ctx.opp,UI.ctx.fmt),{headless:true});S.winner=winner;S.t=30;S.done=true;finishMatch(S);return S}
function chooseCurrent(){const b=G.beasts[UI.lvq[0]],kind=rewardKind(b),d={id:b.id,rev:UI.result.rewardRevision||0};if(kind==='power')ACT.rewardPerk({...d,k:b.offer[0]});else if(kind==='technique')ACT.rewardTechnique({...d,k:legalArenaTechniques(b)[0]});else ACT.rewardTrait({...d,k:b.awaken[0]})}
function clearChoices(){let guard=0;while(remainingRewards().length&&guard++<15)chooseCurrent();if(remainingRewards().length)throw Error('Undelivered choices')}
`);
let passed=0;const test=(name,code)=>{assert.equal(run(code),true,name);passed++;console.log('PASS '+name)};
test('fresh founders start at level one with signatures and no assigned or spendable upgrades',`(()=>{fresh();return clubBeasts().every(b=>b.lvl===1&&!b.rolls&&!b.offer&&!b.awaken.length&&!techniquePoints(b)&&!Object.keys(b.perks).length&&!Object.keys(b.techniques).length&&SPECIES[b.sp].ab)})()`);
test('a fight without a level-up grants XP but no cards, including the first preseason bout',`(()=>{fresh();openNext();const bench=JSON.stringify(clubBeasts().filter(b=>!UI.sel.includes(b.id)));resultFor(0);const captain=G.beasts[UI.sel[0]];return captain.xp>0&&captain.lvl===1&&!remainingRewards().length&&UI.mode==='result'&&!UI.modal&&JSON.stringify(clubBeasts().filter(b=>!UI.sel.includes(b.id)))===bench})()`);
test('only the individual hero who levels in combat earns a choice',`(()=>{fresh();G.campaign.preseason=1;openNext();const b=G.beasts[UI.sel[0]],other=G.beasts[UI.sel[1]];b.xp=xpNeed(b.lvl)-1;const S=resultFor(1),gold=G.gold;finishMatch(S);return b.lvl===2&&other.lvl===1&&UI.lvq.length===1&&UI.lvq[0]===b.id&&rewardKind(b)==='power'&&!b.arenaProgress.pending.won&&G.gold===gold&&UI.mode==='levelup'})()`);
test('independent level-up choices cannot upgrade the bench or be spent twice',`(()=>{const id=UI.lvq[0],b=G.beasts[id],other=clubBeasts().find(b=>!UI.sel.includes(b.id)),snapshot=JSON.stringify(other);const d={id,k:b.offer[0],rev:UI.result.rewardRevision||0};ACT.rewardPerk({...d,id:other.id});if(snapshot!==JSON.stringify(other))return false;ACT.rewardPerk(d);const after=JSON.stringify(b);ACT.rewardPerk(d);return !b.arenaProgress.pending&&b.arenaProgress.chosen===1&&JSON.stringify(b)===after&&UI.mode==='result'})()`);
test('two heroes leveling independently receive one decision each',`(()=>{fresh();G.campaign.preseason=1;openNext();const [a,b]=UI.sel.map(id=>G.beasts[id]);a.xp=b.xp=xpNeed(1)-1;resultFor();if(UI.lvq.length!==2)return false;const first=UI.lvq[0],other=UI.lvq[1];chooseCurrent();if(rewardKind(G.beasts[first])||!rewardKind(G.beasts[other])||UI.lvq.length!==1)return false;chooseCurrent();return !remainingRewards().length&&UI.mode==='result'})()`);
test('level three offers one active ability and not a second passive choice',`(()=>{fresh();openNext();const b=G.beasts[UI.sel[0]];b.lvl=2;b.xp=xpNeed(2)-1;resultFor();if(b.lvl!==3||rewardKind(b)!=='technique'||techniquePoints(b)!==1)return false;chooseCurrent();return techniqueRanks(b)===1&&!b.rolls&&!b.offer&&!rewardKind(b)&&UI.mode==='result'})()`);
test('manual XP and bulk upgrade actions cannot create or spend arena choices',`(()=>{fresh();const b=clubBeasts()[0];gainXp(b,1000);const before=JSON.stringify(G);for(const key of ['keeperTrain','lvall','autoperk','autolearn','learn','technique','perk','awaken','resetTechniques','mastery'])ACT[key]({id:b.id,k:'claws'});autoPick(b);autoTechniques(b);return before===JSON.stringify(G)&&!rewardKind(b)&&!b.rolls&&!b.offer&&!techniquePoints(b)})()`);
test('wins shift exactly five rarity weight points away from Common',`(()=>{const b=clubBeasts()[0],base=arenaRarityWeights(b),win=arenaRarityWeights(b,true);return Math.abs(win[0]-base[0]+5)<1e-9&&Math.abs(win[1]-base[1]-3)<1e-9&&Math.abs(win[2]-base[2]-1.5)<1e-9&&Math.abs(win[3]-base[3]-.5)<1e-9&&Math.abs(win.reduce((a,v)=>a+v,0)-100)<1e-9})()`);
test('seeded card samples produce a modest increase in rare offers after wins',`(()=>{const b=clubBeasts()[0];b.perks={};b.picksTaken=0;const sample=won=>{b.arenaProgress.pending={kind:'power',won};let rare=0,total=0;for(let i=0;i<6000;i++){rollOffer(b);if(new Set(b.offer).size!==3)throw Error('Duplicate offers');for(const k of b.offer){rare+=PERKS[k].t>=2?1:0;total++}}return rare/total};const loss=sample(false),win=sample(true);b.arenaProgress.pending=null;return win>loss+.015&&win<loss+.10})()`);
test('saved winning offers and their bonus survive loading unchanged',`(()=>{fresh('Victory Save');openNext();const b=G.beasts[UI.sel[0]];b.xp=119;resultFor(0);const offer=JSON.stringify(b.offer),id=b.id;save();const slot=G.runId;showRunMenu();loadRunSlot(slot);return UI.mode==='levelup'&&G.beasts[id].arenaProgress.pending.won&&JSON.stringify(G.beasts[id].offer)===offer&&modalReward().includes('VICTORY BONUS')})()`);
test('a fresh campaign preserves the previous campaign and can be switched back',`(()=>{const oldId=G.runId,oldName=G.name,oldGold=G.gold;save();fresh('Another Team');save();const newId=G.runId;showRunMenu();if(!loadRunSlot(oldId)||G.name!==oldName||G.gold!==oldGold)return false;loadRunSlot(newId);return G.name==='Another Team'&&G.runId!==oldId&&clubBeasts().every(b=>!b.arenaProgress.pending)})()`);
test('named checkpoints remain immutable and load into a separate playable run',`(()=>{const source=G.runId;G.gold=75;saveCheckpoint('Before the final');const checkpoint=readRunLibrary().slots.find(s=>s.label==='Before the final');G.gold=150;save();loadRunSlot(checkpoint.id);const branch=G.runId;if(G.gold!==75||branch===source||branch===checkpoint.id)return false;G.gold=12;save();const library=readRunLibrary();return library.slots.find(s=>s.id===checkpoint.id).game.gold===75&&library.slots.find(s=>s.id===source).game.gold===150&&library.slots.find(s=>s.id===branch).game.gold===12})()`);
test('quitting a fight saves its preparation without granting a result or reward',`(()=>{fresh('Paused Run');openNext();UI.mode='battle';BT={raf:1,paused:false};const gold=G.gold,xp=clubBeasts()[0].xp;ACT.runQuit();if(UI.mode!=='menu'||G||BT)return false;const id=readRunLibrary().activeId;loadRunSlot(id);return UI.mode==='prematch'&&G.gold===gold&&clubBeasts()[0].xp===xp&&!UI.result&&!remainingRewards().length})()`);
test('saving a report resumes the exact pending hero rather than replaying the bout',`(()=>{G.beasts[UI.sel[0]].xp=119;resultFor();const id=UI.lvq[0],gold=G.gold;ACT.rewardLater();ACT.runQuit();const slot=readRunLibrary().activeId;loadRunSlot(slot);if(UI.mode!=='result'||G.gold!==gold||UI.lvq[0]!==id)return false;ACT.resnext();return UI.mode==='levelup'&&UI.modal.k==='reward'&&UI.lvq[0]===id})()`);
test('legacy campaigns retain learned skills and spread unspent choices across future arena level-ups',`(()=>{fresh('Legacy Import');const old=copyRun(G),b=old.beasts[old.clubs.P.roster[0]];delete old.arenaRules;for(const id of old.clubs.P.roster)delete old.beasts[id].arenaProgress;b.lvl=7;b.perks={claws:2};b.techniques={seismic:1};b.rolls=7;b.offer=['hide','recovery','claws'];migrateArenaProgress(old);return b.perks.claws===2&&b.techniques.seismic===1&&b.arenaProgress.bank.powers===7&&!b.rolls&&!b.offer&&!b.arenaProgress.pending})()`);
test('a legacy paid result retains a single pending choice on migration',`(()=>{const old=copyRun(G),id=old.clubs.P.roster[0],b=old.beasts[id];delete b.arenaProgress;b.lvl=2;b.rolls=3;b.perks={};b.techniques={};b.offer=['hide','claws','recovery'];old.resume={mode:'result',lvq:[id],result:{ctx:{kind:'trial',trial:0,fmt:1},winner:1,rows:[{bid:id,team:0}]}};migrateArenaProgress(old);return b.rolls===1&&b.arenaProgress.pending.kind==='power'&&b.arenaProgress.bank.powers===2&&JSON.stringify(b.offer)==='["hide","claws","recovery"]'})()`);
test('storage failure keeps the running campaign open and existing saves intact',`(()=>{fresh('Storage Safety');save();const previous=localStorage.setItem,id=G.runId,saved=localStorage.getItem(RUN_LIBRARY_KEY);localStorage.setItem=(k,v)=>{if(k===RUN_LIBRARY_KEY)throw Error('quota');previous(k,v)};G.gold=18;ACT.runQuit();localStorage.setItem=previous;return G?.runId===id&&UI.mode==='hub'&&localStorage.getItem(RUN_LIBRARY_KEY)===saved})()`);
test('invalid imports leave all campaign slots and the current run intact',`(()=>{const before=localStorage.getItem(RUN_LIBRARY_KEY),id=G.runId;return !importRunCode('not-a-save')&&G.runId===id&&localStorage.getItem(RUN_LIBRARY_KEY)===before})()`);
test('new campaign completes preseason and a league season with individually delivered upgrades',`(()=>{fresh('Season Journey');let count=0;while(G.season===1&&count++<45){if(UI.mode==='hub')openNext();if(UI.mode==='draft')while(G.draft.picks.length<5)draftPick(G.draft.offers[0]);if(UI.mode==='prematch'){startMatch(false);clearChoices();resultNext()}if(UI.mode==='cupdone')finishCupDay(null)}return G.season===2&&G.history.length===1&&G.campaign.preseason===4&&clubBeasts().some(b=>b.arenaProgress?.chosen>0)&&Number.isFinite(G.gold)})()`);
test('supplies cannot bypass arena progression or sell unusable training items',`(()=>{fresh();G.gold=1000;G.campaign.earnedGold=300;G.cons={manual:2,tome:1,dice:1};const b=clubBeasts()[0],before=JSON.stringify(G);for(const k of ['manual','tome','dice']){ACT.cbuy({k});ACT.use({id:b.id,k})}const html=viewShop();return JSON.stringify(G)===before&&!html.includes('data-k="manual"')&&!html.includes('data-k="tome"')&&!html.includes('data-k="dice"')})()`);
console.log(`\n${passed} campaign checks passed.`);
