'use strict';
// Original procedural score: organic ensemble timbres, a recurring theme, and adaptive orchestration.
const SCORE={fx:null,started:false,lastHit:0,level:0};
actx=function(){if(MUS.ctx){if(MUS.ctx.state==='suspended'&&!document.hidden)MUS.ctx.resume().catch(()=>{});return MUS.ctx}const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;let c;try{c=new AC()}catch{return null}MUS.ctx=c;
 const limiter=c.createDynamicsCompressor();limiter.threshold.value=-15;limiter.knee.value=18;limiter.ratio.value=7;limiter.attack.value=.005;limiter.release.value=.38;
 const bus=c.createGain(),master=c.createGain();master.gain.value=MUS.on?MUS.vol*.64:0;const low=c.createBiquadFilter();low.type='lowpass';low.frequency.value=7800;
 const rev=c.createConvolver();rev.buffer=impulse(c,3.8,3.3);const wet=c.createGain();wet.gain.value=.25;bus.connect(low);low.connect(limiter);low.connect(rev);rev.connect(wet);wet.connect(limiter);limiter.connect(master);master.connect(c.destination);
 const delay=c.createDelay(.6);delay.delayTime.value=.28;const dg=c.createGain();dg.gain.value=.085;low.connect(delay);delay.connect(dg);dg.connect(limiter);
 const effects=c.createGain(),fxlimit=c.createDynamicsCompressor();effects.gain.value=.20;fxlimit.threshold.value=-12;effects.connect(fxlimit);fxlimit.connect(c.destination);SCORE.fx=effects;MUS.bus=bus;MUS.master=master;return c};
function stageVoice(c,out,time,duration,volume,pan=0,attack=.12,release=.5){const gain=c.createGain(),stereo=c.createStereoPanner();stereo.pan.value=pan;gain.connect(stereo);stereo.connect(out);gain.gain.setValueAtTime(0,time);gain.gain.linearRampToValueAtTime(volume,time+Math.min(attack,duration*.35));gain.gain.setValueAtTime(volume*.83,time+Math.max(attack,duration*.72));gain.gain.linearRampToValueAtTime(0,time+duration+release);return gain}
iStrings=function(c,o,t,notes,dur,v){notes.forEach((n,i)=>{const pan=notes.length>1?(i/(notes.length-1)-.5)*1.25:0,env=stageVoice(c,o,t,dur,.027*v,pan,.7,.85),lp=c.createBiquadFilter();lp.type='lowpass';lp.frequency.value=1250+(i%2)*380;lp.Q.value=.4;lp.connect(env);[-8,7].forEach((det,j)=>{const s=aosc(c,j?'sawtooth':'triangle',mf(n),t,t+dur+1,det);const vibrato=aosc(c,'sine',4.7+i*.23,t,t+dur+1),vg=c.createGain();vg.gain.value=mf(n)*.0025;vibrato.connect(vg);vg.connect(s.frequency);s.connect(lp)})})};
iBrass=function(c,o,t,n,dur,v,br=.8){const env=stageVoice(c,o,t,dur,.065*v,-.15,.09,.35),lp=c.createBiquadFilter();lp.type='lowpass';lp.Q.value=.65;lp.frequency.setValueAtTime(mf(n)*1.3,t);lp.frequency.linearRampToValueAtTime(mf(n)*(3.3+br*2),t+.16);lp.frequency.linearRampToValueAtTime(mf(n)*2,t+Math.max(.2,dur));lp.connect(env);[-5,5].forEach(det=>aosc(c,'sawtooth',mf(n),t,t+dur+.5,det).connect(lp));const fundamental=aosc(c,'sine',mf(n),t,t+dur+.5);fundamental.connect(env)};
iPluck=function(c,o,t,n,v){const env=stageVoice(c,o,t,.14,.10*v,.45,.008,.5),lp=c.createBiquadFilter();lp.type='lowpass';lp.frequency.setValueAtTime(2500,t);lp.frequency.exponentialRampToValueAtTime(400,t+.28);lp.connect(env);aosc(c,'triangle',mf(n),t,t+.75).connect(lp);const overtone=aosc(c,'sine',mf(n)*2.003,t,t+.45),og=c.createGain();og.gain.value=.25;overtone.connect(og);og.connect(lp)};
iChoir=function(c,o,t,notes,dur,v){notes.forEach((n,i)=>{const env=stageVoice(c,o,t,dur,.028*v,(i-1)*.35,.9,.9),osc=aosc(c,'sawtooth',mf(n),t,t+dur+1.1,i*3-3);[550,1050,2300].forEach((f,j)=>{const bp=c.createBiquadFilter(),gg=c.createGain();bp.type='bandpass';bp.frequency.value=f;bp.Q.value=4;gg.gain.value=[1,.42,.1][j];osc.connect(bp);bp.connect(gg);gg.connect(env)})})};
function lowPulse(c,o,t,n,v){const env=stageVoice(c,o,t,.32,.10*v,-.1,.03,.4),s=aosc(c,'sine',mf(n),t,t+.8);s.connect(env);const lp=c.createBiquadFilter();lp.type='lowpass';lp.frequency.value=180;lp.connect(env);aosc(c,'triangle',mf(n)*.5,t,t+.8).connect(lp)}
function taiko(c,o,t,v,pitch=70){iDrum(c,o,t,v*.52,pitch);const env=stageVoice(c,o,t,.07,.10*v,-.5,.001,.45),bp=c.createBiquadFilter();bp.type='bandpass';bp.frequency.value=260;bp.Q.value=1.2;bp.connect(env);anoise(c,t,.6).connect(bp)}
const HARMONY=[[50,57,62,65],[46,53,58,62],[53,60,65,69],[48,55,60,64],[50,57,62,65],[43,50,58,62],[45,52,57,61],[50,57,62,69]];
const THEME=[[74,2],[69,1],[72,1],[77,2],[76,1],[72,1],[74,3],[69,1],[67,2],[65,2]];
function theme(c,o,t,b,index,v=1){const bars=[[[74,2],[69,1],[72,1]],[[77,2],[76,1],[72,1]],[[74,3],[69,1]],[[67,2],[65,2]]];let pos=0;bars[index%4].forEach(([n,d])=>{iBrass(c,o,t+pos*b,n,d*b*.91,.6*v,.4);pos+=d})}
TRACKS.club={bpm:66,bar(c,o,t,b,i){const tones=HARMONY[Math.floor(i/2)%8];iStrings(c,o,t,tones.slice(0,3),b*3.85,.65);if(i%2===0)iChoir(c,o,t,tones.slice(1),b*7.8,.36);[0,1.5,2.5,3.25].forEach((p,j)=>iPluck(c,o,t+b*p,tones[(j+1)%4]+12,.25));if(i%4===0)lowPulse(c,o,t,tones[0]-12,.6);if(i%16>=12)theme(c,o,t,b,i,.30)}};
TRACKS.prelude={bpm:82,bar(c,o,t,b,i){const tones=HARMONY[i%8],build=Math.min(1,i/8);iStrings(c,o,t,tones,b*3.8,.8);[0,1.5,2,3.5].forEach((p,j)=>{taiko(c,o,t+b*p,.4+build*.25,j%2?95:65);lowPulse(c,o,t+b*p,tones[0]-12,.55)});for(let j=0;j<8;j++)iPluck(c,o,t+b*j/2,tones[1+j%3]+12,.25+build*.2);if(i%4>=2)iChoir(c,o,t,tones.slice(1),b*3.8,.45);if(i%4===3)iSwell(c,o,t+b*2,b*2,.45)}};
TRACKS.battle={bpm:112,bar(c,o,t,b,i){const tones=HARMONY[i%8],S=BT?.S;const progress=S?Math.min(1,S.t/50):0;const alive=S?S.units.filter(u=>u.alive&&!u.summon).length:10;const tension=Math.max(progress,alive<=4?.8:0);SCORE.level=tension;
 iStrings(c,o,t,tones.slice(0,3),b*3.9,.9);if(i>=4||tension>.6)iChoir(c,o,t,tones.slice(1),b*3.8,.45+tension*.2);
 [0,.75,1.5,2,2.75,3.5].forEach((p,j)=>{taiko(c,o,t+b*p,j%3===0?.95:.48,j%2?93:58);lowPulse(c,o,t+b*p,tones[0]-12,j%3===0?.95:.6)});
 for(let j=0;j<8;j++)iPluck(c,o,t+b*j/2,tones[[1,2,3,2,1,2,3,1][j]]+12,.38+tension*.18);
 if(i%8>=4)theme(c,o,t,b,i,.75);else if(i%2===0)tones.slice(0,3).forEach(n=>iBrass(c,o,t+b*.05,n,b*1.5,.3,.5));
 if(tension>.5){[1,3].forEach(p=>iSnare(c,o,t+b*p,.32));for(let j=0;j<8;j++)iHat(c,o,t+b*j/2,.2)}
 if(i%4===3){iSwell(c,o,t+b*2,b*2,.5);[3,3.5,3.75].forEach((p,j)=>taiko(c,o,t+b*p,.4+j*.16,100))}if(i%8===0)iCrash(c,o,t,.27)
}};
TRACKS.victory={bpm:86,bar(c,o,t,b,i){const chords=[[50,57,62,66],[47,54,59,62],[43,50,55,59],[45,52,57,61]],ch=chords[i%4];iStrings(c,o,t,ch,b*3.85,.9);iChoir(c,o,t,ch.slice(1),b*3.85,.6);if(i<8){taiko(c,o,t,.8,67);taiko(c,o,t+b*2,.5,90);let pos=0;[[74,1.5],[78,.5],[81,1],[86,1]].forEach(([n,d])=>{iBrass(c,o,t+pos*b,n-(i%4===2?7:0),d*b*.95,.48,.7);pos+=d});if(i===0)iCrash(c,o,t,.45)}else [0,2].forEach((p,j)=>iPluck(c,o,t+p*b,ch[j+1]+12,.3))}};
TRACKS.honor={bpm:58,bar(c,o,t,b,i){const ch=HARMONY[i%8];iStrings(c,o,t,ch.slice(0,3),b*3.9,.6);iChoir(c,o,t,ch.slice(1),b*3.8,.25);if(i%2===0)theme(c,o,t,b,i,.3);[0,2.5].forEach((p,j)=>iPluck(c,o,t+p*b,ch[j+1]+12,.24));if(i%4===0)taiko(c,o,t,.3,54)}};
music=function(name){name=name||'club';if(MUS.name===name&&MUS.node)return;MUS.name=name;clearInterval(MUS.timer);const c=actx();if(!c)return;if(MUS.node){const old=MUS.node;old.gain.cancelScheduledValues(c.currentTime);old.gain.setValueAtTime(old.gain.value,c.currentTime);old.gain.linearRampToValueAtTime(0,c.currentTime+1.4);setTimeout(()=>old.disconnect(),1800)}MUS.node=null;if(!MUS.on||!TRACKS[name])return;const g=c.createGain();g.gain.setValueAtTime(0,c.currentTime);g.gain.linearRampToValueAtTime(.9,c.currentTime+1.3);g.connect(MUS.bus);MUS.node=g;MUS.track=TRACKS[name];MUS.next=c.currentTime+.1;MUS.bar=0;
 const tick=()=>{if(MUS.node!==g||c.state!=='running'||document.hidden)return;if(MUS.next<c.currentTime-.1)MUS.next=c.currentTime+.05;let n=0;while(MUS.next<c.currentTime+.5&&n++<2){const beat=60/MUS.track.bpm;MUS.track.bar(c,g,MUS.next,beat,MUS.bar++);MUS.next+=beat*4}};tick();MUS.timer=setInterval(tick,140)};
musToggle=function(){MUS.on=!MUS.on;musSave();const c=actx(),name=MUS.name||'club';if(c)MUS.master.gain.setTargetAtTime(MUS.on?MUS.vol*.64:0,c.currentTime,.12);if(!MUS.on){clearInterval(MUS.timer);if(MUS.node){const old=MUS.node;old.gain.setTargetAtTime(0,c.currentTime,.12);setTimeout(()=>old.disconnect(),800);MUS.node=null}}else{MUS.name=null;music(name)}};
function playCue(kind){if(!PREFS.sfx)return;const c=actx();if(!c||c.state!=='running')return;const t=c.currentTime+.005,o=SCORE.fx;if(kind==='upgrade'){[62,69,74,77,81].forEach((n,i)=>iPluck(c,o,t+i*.08,n,.8));iChoir(c,o,t,[62,69,74],1.2,.28)}else if(kind==='hit'){if(t-SCORE.lastHit<.095)return;SCORE.lastHit=t;taiko(c,o,t,.20,120)}else if(kind==='cast'){iPluck(c,o,t,81,.4);iSwell(c,o,t,.18,.18)}else{iPluck(c,o,t,74,.15)}}
const soundHit=hit;hit=function(S,src,target,raw,o={}){const result=soundHit(S,src,target,raw,o);if(!S.headless&&BT?.S===S)playCue('hit');return result};
const soundCast={...CAST};Object.keys(CAST).forEach(k=>{CAST[k]=function(S,u){soundCast[k](S,u);if(!S.headless&&BT?.S===S)playCue('cast')}});
document.addEventListener('pointerdown',()=>{if(!SCORE.started){SCORE.started=true;music(UI.mode==='battle'?'battle':UI.mode==='prematch'?'prelude':'club')}else actx()},{passive:true});
document.addEventListener('click',e=>{if(e.target.closest('button:not(:disabled)')&&!e.target.closest('[data-act="perk"],[data-act="mastery"],[data-act="facility"],[data-act="music"]'))playCue('click')},{passive:true});
document.addEventListener('visibilitychange',()=>{if(!MUS.ctx)return;if(document.hidden)MUS.ctx.suspend().catch(()=>{});else if(SCORE.started)MUS.ctx.resume().catch(()=>{})});
document.addEventListener('input',e=>{if(e.target.id==='vol'&&MUS.master)setTimeout(()=>MUS.master.gain.setTargetAtTime(MUS.on?MUS.vol*.64:0,MUS.ctx.currentTime,.07),0)});
